CREATE TABLE `merchant_apply` (
  `merchantApplyId` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `merchantId` char(64) DEFAULT NULL COMMENT '商户编号',
  `merchantName` varchar(255) DEFAULT NULL COMMENT '商户名称',
  `merchantStatus` varchar(16) DEFAULT NULL COMMENT '商户状态:NORMAL-正常 、EXPIRED-过期、FREEZED-过期',
  `contactName` varchar(64) DEFAULT NULL COMMENT '联系人姓名',
  `contactPhone` varchar(32) DEFAULT NULL COMMENT '联系人手机号',
  `contractStartDate` date DEFAULT NULL COMMENT '合同开始时间',
  `contractEndDate` date DEFAULT NULL COMMENT '合同截止时间',
  `provinceId` int(10) unsigned DEFAULT NULL COMMENT '省/直辖市编号',
  `cityId` int(10) unsigned DEFAULT NULL COMMENT '市/直辖市编号',
  `areaId` int(10) unsigned DEFAULT NULL COMMENT '县/区编号',
  `detailAddr` varchar(128) DEFAULT NULL COMMENT '商户详细地址',
  `firstOrgId` bigint(20) unsigned DEFAULT NULL COMMENT '一级机构编号',
  `secondOrgId` bigint(20) unsigned DEFAULT NULL COMMENT '二级机构编号',
  `thirdOrgId` bigint(20) unsigned DEFAULT NULL COMMENT '三级机构编号',
  `incomingId` bigint(20) DEFAULT NULL COMMENT '进件记录编号',
  `incomingType` varchar(16) DEFAULT NULL COMMENT '进件记录类型',
  `auditJnlNo` bigint(20) unsigned DEFAULT NULL COMMENT '审核批次',
  `auditStatus` varchar(16) DEFAULT NULL COMMENT '审核状态',
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` datetime DEFAULT NULL,
  `acctNo` varchar(64) DEFAULT NULL COMMENT '结算账号',
  `acctType` varchar(16) DEFAULT NULL COMMENT '结算账号类型',
  `acctName` varchar(64) DEFAULT NULL COMMENT '结算账号开户名',
  `openBankName` varchar(32) DEFAULT NULL COMMENT '结算账号开户银行',
  `openBankId` varchar(32) DEFAULT NULL COMMENT '结算账号开户银行编号',
  `openProvinceId` varchar(32) DEFAULT NULL,
  `openProvinceName` varchar(32) DEFAULT NULL,
  `openCityId` varchar(32) DEFAULT NULL,
  `openCityName` varchar(32) DEFAULT NULL,
  `openNetId` varchar(32) DEFAULT NULL,
  `openNetName` varchar(32) DEFAULT NULL,
  `isSignCoupon` tinyint(1) DEFAULT NULL COMMENT '是否支持优惠券',
  `isSignOnlinePay` tinyint(1) DEFAULT NULL COMMENT '是否支持在线买单',
  PRIMARY KEY (`merchantApplyId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8