spring:
  application:
    name: hh-life-dubbo-api-merchant

# ------------------  dubbo配置 ------------------
dubbo:
  application:
    # dubbo应用名称
    name: dubbo-consumer-hhlife-merchant
  # zk注册中心
  registry:
    address: zookeeper://127.0.0.1:2181
    group: dubbo
    client: zkclient

server:
  port: 10000