spring:
  application:
    name: hh-life-dubbo-api-opcenter

# ------------------  dubbo配置 ------------------
dubbo:
  application:
    # dubbo应用名称
    name: dubbo-consumer-hhlife-opcenter
  # zk注册中心
  registry:
    address: zookeeper://192.168.5.110:2181
    group: dubbo
    client: zkclient

server:
  port: 10000